// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import ConditionalInputController from "./conditional_input_controller"
application.register("conditional-input", ConditionalInputController)

import CopropertyInfoController from "./coproperty_info_controller"
application.register("coproperty-info", CopropertyInfoController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

// import JihaneController from "./jihane_controller"
// application.register("jihane", JihaneController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

// chartjs

import Chart from 'stimulus-chartjs'
application.register('chart', Chart)

import Doughnut from 'stimulus-chartjs'
application.register('doughnut', Doughnut)

import Line from 'stimulus-chartjs'
application.register('line', Line)

import Pie from 'stimulus-chartjs'
application.register('pie', Pie)

import PolarArea from 'stimulus-chartjs'
application.register('polar-area', PolarArea)

import Radar from 'stimulus-chartjs'
application.register('radar', Radar)

import Bar from 'stimulus-chartjs'
application.register('bar', Bar)

import Bubble from 'stimulus-chartjs'
application.register('bubble', Bubble)

import Scatter from 'stimulus-chartjs'
application.register('scatter', Scatter)

import HorizontalBar from 'stimulus-chartjs'
application.register('horizontal-bar', HorizontalBar)

import StackedBar from 'stimulus-chartjs'
application.register('stacked-bar', StackedBar)

// import StackedHorizontalBar from 'stimulus-chartjs'
// application.register('stacked-horizontal-bar', StackedHorizontalBar)

// import StackedArea from 'stimulus-chartjs'
// application.register('stacked-area', StackedArea)

// import StackedLine from 'stimulus-chartjs'
// application.register('stacked-line', StackedLine)

// import StackedRadar from 'stimulus-chartjs'
// application.register('stacked-radar', StackedRadar)

// import StackedBar100 from 'stimulus-chartjs'
// application.register('stacked-bar-100', StackedBar100)

// import StackedHorizontalBar100 from 'stimulus-chartjs'
// application.register('stacked-horizontal-bar-100', StackedHorizontalBar100)

// import StackedArea100 from 'stimulus-chartjs'
// application.register('stacked-area-100', StackedArea100)

// import StackedLine100 from 'stimulus-chartjs'
// application.register('stacked-line-100', StackedLine100)

// import StackedRadar100 from 'stimulus-chartjs'
// application.register('stacked-radar-100', StackedRadar100)

// import StackedBar100Percent from 'stimulus-chartjs'
// application.register('stacked-bar-100-percent', StackedBar100Percent)

// import StackedHorizontalBar100Percent from 'stimulus-chartjs'
// application.register('stacked-horizontal-bar-100-percent', StackedHorizontalBar100Percent)

// import StackedArea100Percent from 'stimulus-chartjs'
// application.register('stacked-area-100-percent', StackedArea100Percent)

// import StackedLine100Percent from 'stimulus-chartjs'
// application.register('stacked-line-100-percent', StackedLine100Percent)

// import StackedRadar100Percent from 'stimulus-chartjs'
// application.register('stacked-radar-100-percent', StackedRadar100Percent)

// import StackedHorizontalBar100PercentStacked from 'stimulus-chartjs'
// application.register('stacked-horizontal-bar-100-percent-stacked', StackedHorizontalBar100PercentStacked)

// import StackedArea100PercentStacked from 'stimulus-chartjs'
// application.register('stacked-area-100-percent-stacked', StackedArea100PercentStacked)

// import StackedLine100PercentStacked from 'stimulus-chartjs'
// application.register('stacked-line-100-percent-stacked', StackedLine100PercentStacked)

// import StackedRadar100PercentStacked from 'stimulus-chartjs'
// application.register('stacked-radar-100-percent-stacked', StackedRadar100PercentStacked)

// import StackedBar100PercentStacked from 'stimulus-chartjs'
// application.register('stacked-bar-100-percent-stacked', StackedBar100PercentStacked)

// import StackedHorizontalBar100PercentStacked from 'stimulus-chartjs'
// application.register('stacked-horizontal-bar-100-percent-stacked', StackedHorizontalBar100PercentStacked)

// import StackedArea100PercentStacked from 'stimulus-chartjs'
// application.register('stacked-area-100-percent-stacked', StackedArea100PercentStacked)

// import StackedLine100PercentStacked from 'stimulus-chartjs'
// application.register('stacked-line-100-percent-stacked', StackedLine100PercentStacked)

// import StackedRadar100PercentStacked from 'stimulus-chartjs'
// application.register('stacked-radar-100-percent-stacked', StackedRadar100PercentStacked)

// import StackedBar100PercentStacked from 'stimulus-chartjs'
// application.register('stacked-bar-100-percent-stacked', StackedBar100PercentStacked)

// import StackedHorizontalBar100PercentStacked from 'stimulus-chartjs'
// application.register('stacked-horizontal-bar-100-percent-stacked', StackedHorizontalBar100PercentStacked)

// import StackedArea100PercentStacked from 'stimulus-chartjs'
// application.register('stacked-area-100-percent-stacked', StackedArea100PercentStacked)

// import StackedLine100PercentStacked from 'stimulus-chartjs'
// application.register('stacked-line-100-percent-stacked', StackedLine100PercentStacked)

// import StackedRadar100PercentStacked from 'stimulus-chartjs'
// application.register('stacked-radar-100-percent-stacked', StackedRadar100PercentStacked)

// import StackedBar100PercentStacked from 'stimulus-chartjs'
// application.register('stacked-bar-100-percent-stacked', StackedBar100PercentStacked)

// import StackedHorizontalBar100PercentStacked from 'stimulus-chartjs'
// application.register('stacked-horizontal-bar-100-percent-stacked', StackedHorizontalBar100PercentStacked)

// import StackedArea100PercentStacked from 'stimulus-chartjs'
// application.register('stacked-area-100-percent-stacked', StackedArea100PercentStacked)

// import StackedLine100PercentStacked from 'stimulus-chartjs'
// application.register('stacked-line-100-percent-stacked', StackedLine100PercentStacked)

// import StackedRadar100PercentStacked from 'stimulus-chartjs'
// application.register('stacked-radar-100-percent-stacked', StackedRadar100PercentStacked)

// import StackedBar100PercentStacked from 'stimulus-chartjs'
// application.register('stacked-bar-100-percent-stacked', StackedBar100PercentStacked)

// import StackedHorizontalBar100PercentStacked from 'stimulus-chartjs'
// application.register('stacked-horizontal-bar-100-percent-stacked', StackedHorizontalBar100PercentStacked)

// import StackedArea100PercentStacked from 'stimulus-chartjs'
// application.register('stacked-area-100-percent-stacked', StackedArea100PercentStacked)

// import StackedLine100PercentStacked from 'stimulus-chartjs'
// application.register('stacked-line-100-percent-stacked', StackedLine100PercentStacked)
