// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import ConditionalInputController from "./conditional_input_controller"
application.register("conditional-input", ConditionalInputController)

import CopropertyInfoController from "./coproperty_info_controller"
application.register("coproperty-info", CopropertyInfoController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

// import JihaneController from "./jihane_controller"
// application.register("jihane", JihaneController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

// chartjs

import Chart from 'stimulus-chartjs'
application.register('chart', Chart)

import Doughnut from 'stimulus-chartjs'
application.register('doughnut', Doughnut)

const config = {
  type: 'doughnut',
  data: data,
};
